name: Run All Tests
on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci --force
      - name: Run Jest
        run: npm run test
